### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by NickBolles** [ui-router/visualizer#1]
I am getting the following errors when trying to require the visualizer into my app.

[18:09:30] gulp-notify: [Compile Error] Error: Cannot find module '!!./../../node_modules/css-loader/index.js!./transitionHistory.css' from 'c:\Development\foursee\app\node_modules\ui-router-visualizer\release'
[18:09:30] gulp-notify: [Compile Error] Error: Cannot find module '!!./../../node_modules/css-loader/index.js!./vis.css' from 'c:\Development\foursee\app\node_modules\ui-router-visualizer\release'

**Comment by christopherthielen** [comment]
What steps did you take so far to include the visualizer? 
`npm install --save ui-router-visualizer`?

What is your build setup? Webpack bundler?

How are you `require`ing the lib?
`var visualizer = require("ui-router-visualizer");`?

Any other details you can provide?

---

The errors you posted are related to the embedded CSS files, but I thought the bundled version (`visualizer.js`) would handle those automatically...

**Comment by NickBolles** [comment]
I am using npm to install like you had

I am using gulp to browserify my files. Using `require('ui-router-visualization');` and then in my angular module 
`Angular.module('app',  ['ui.router', 'ui.router.visualizer']);`

Is the issue that I'm using browserify? 

It looks like the visualization.js is trying to require the css-loader file, which is not installed in npm. And even if I do install it with `npm install css-loader` it still doesn't work.

**Comment by christopherthielen** [comment]
I think browserify is trying to process the hot module replacement code that webpack is generating.  I removed that code from the built file and put it on a gist:   https://rawgit.com/christopherthielen/ddd5e28f6a206a8812fae9b48c0ff2a2/raw/ca1a3c005393325ef8b347b7b6560ecfe05cba60/visualizer.js

Can you try downloading that file and replacing the one in node_modules with the one in my gist?

```
cd node_modules/ui-router-visualizer/release
rm visualizer.js
curl -O https://rawgit.com/christopherthielen/ddd5e28f6a206a8812fae9b48c0ff2a2/raw/ca1a3c005393325ef8b347b7b6560ecfe05cba60/visualizer.js
```

**Comment by NickBolles** [comment]
It builds now. But I am now getting the following error on the app boot

```
ncaught TypeError: s.$$state is not a function(anonymous function) @ visualizer.js:310statevis_module_1.app.service.pollStates @ visualizer.js:310(anonymous function) @ visualizer.js:330instantiate @ angular.js:4619(anonymous function) @ angular.js:4459invoke @ angular.js:4604enforcedReturnValue @ angular.js:4443invoke @ angular.js:4604(anonymous function) @ angular.js:4403getService @ angular.js:4550injectionArgs @ angular.js:4574invoke @ angular.js:4596(anonymous function) @ angular.js:4412forEach @ angular.js:321createInjector @ angular.js:4412doBootstrap @ angular.js:1691angular.resumeBootstrap @ angular.js:1720maybeBootstrap @ hint.js:569setTimeout (async)maybeBootstrap @ hint.js:565
cordova.js:909 deviceready has not fired after 5 seconds.
```

**Comment by christopherthielen** [comment]
`$$state()` landed in version ui-router 1.0.0-alpha.1... are you using alpha.1 or later?

**Comment by NickBolles** [comment]
No i am using `0.2.17`, but inspecting the $state.get() call, it looks like abstract states do not have the $$state function. Will using 1.0.0-alpha 1 or later fix that?
![ui-visualization debug](https://cloud.githubusercontent.com/assets/7891759/14695226/ba1d6fbc-0735-11e6-8dde-fc06458c717e.PNG)

**Comment by christopherthielen** [comment]
I think only the unnamed root state `""` is missing the $$state method (Also, if the root state is missing $$state, that's something I should fix in a later alpha)

The visualizer only works with 1.0.0 versions because it relies on the `$transitions` service

**Comment by NickBolles** [comment]
Gotcha. I see now that the right most state ("menu") is abstract and has the $$state.
 I will migrate to 1.0.0 when I can. Thank you!
